# Additional configuration and default values at https://github.com/gakonst/foundry/tree/master/config
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base = { url = "https://api.basescan.org/api", key = "${BASESCAN_KEY}", chain = "base" }
mainnet = { url = "https://api.etherscan.io/api", key = "${ETHERSCAN_KEY}", chain = "mainnet" }

[fmt]
number_underscore = "thousands"
