# Additional configuration and default values at https://github.com/gakonst/foundry/tree/master/config
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
fantom = "${FANTOM_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
arbitrum = { url = "https://api.arbiscan.io/api", key = "${ARBISCAN_KEY}", chain = "arbitrum" }
base = { url = "https://api.basescan.org/api", key = "${BASESCAN_KEY}", chain = "base" }
fantom = { url = "https://api.ftmscan.com/api", key = "${FTMSCAN_KEY}", chain = "fantom" }
mainnet = { url = "https://api.etherscan.io/api", key = "${ETHERSCAN_KEY}", chain = "mainnet" }

[fmt]
number_underscore = "thousands"
